/**
 * Technician mileage log (migration 0138) — a manual entry log, PLUS
 * (migration 0141) an optional auto-sync path that derives entries from a
 * technician's completed tickets. Manual entries are typed in directly;
 * auto-synced ones (source: "auto") are generated by syncMileageFromTickets
 * below, reusing the same office-to-customer distance calculator already
 * used on the ticket detail page (mapEngine.ts's computeOfficeDistanceMiles)
 * rather than any new mileage math. Edited on Accounting Dashboard's
 * Mileage tab.
 */

import { supabase } from "./client";
import { getCompanyMapProvider } from "./companySettings";
import { computeOfficeDistanceMiles, type MileageTicketInput } from "@/lib/mapEngine";
import { statusGroupOf } from "@/lib/ticketData";

export interface MileageEntry {
  id: string;
  /** Null when this entry was auto-synced for a technician name that
   *  matched no real profile — see technicianName and migration 0142. */
  profileId: string | null;
  /** Raw ticket technician text, set only when profileId is null — the
   *  display fallback for an unmatched auto-synced entry. Manual entries
   *  (which always require picking a real profile) never set this. */
  technicianName: string | null;
  branch: string;
  workDate: string;
  address: string;
  contactNumber: string | null;
  email: string | null;
  totalMileage: number;
  googleMapLink: string | null;
  createdByName: string | null;
  createdAt: string;
  ticketId: string | null;
  /** Human-readable ticket number, set only on auto-synced entries — see migration 0143. */
  ticketNo: string | null;
  source: "manual" | "auto";
}

function mapRow(r: any): MileageEntry {
  return {
    id: r.id,
    profileId: r.profile_id ?? null,
    technicianName: r.technician_name ?? null,
    branch: r.branch,
    workDate: r.work_date,
    address: r.address,
    contactNumber: r.contact_number ?? null,
    email: r.email ?? null,
    totalMileage: Number(r.total_mileage) || 0,
    googleMapLink: r.google_map_link ?? null,
    createdByName: r.created_by_name ?? null,
    createdAt: r.created_at,
    ticketId: r.ticket_id ?? null,
    ticketNo: r.ticket_no ?? null,
    source: r.source === "auto" ? "auto" : "manual",
  };
}

/** All mileage entries for the caller's company (RLS-scoped), newest first. */
export async function getMileageEntries(): Promise<MileageEntry[]> {
  const { data, error } = await supabase
    .from("mileage_entries")
    .select("id, profile_id, technician_name, branch, work_date, address, contact_number, email, total_mileage, google_map_link, created_by_name, created_at, ticket_id, ticket_no, source")
    .order("work_date", { ascending: false });
  if (error) {
    console.error("getMileageEntries error:", error.message);
    return [];
  }
  return (data ?? []).map(mapRow);
}

export async function addMileageEntry(input: {
  profileId: string;
  branch: string;
  workDate: string;
  address: string;
  contactNumber: string;
  email: string;
  totalMileage: number;
  googleMapLink: string;
  createdByName: string;
}): Promise<void> {
  const { error } = await supabase.from("mileage_entries").insert({
    profile_id: input.profileId,
    branch: input.branch,
    work_date: input.workDate,
    address: input.address,
    contact_number: input.contactNumber || null,
    email: input.email || null,
    total_mileage: input.totalMileage,
    google_map_link: input.googleMapLink || null,
    created_by_name: input.createdByName,
  });
  if (error) throw new Error(error.message);
}

export async function deleteMileageEntry(id: string): Promise<void> {
  const { error } = await supabase.from("mileage_entries").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

export interface MileageSyncResult {
  created: number;
  skipped: number;
  errors: string[];
  /** Completed tickets whose technician text didn't match ANY technician
   *  passed in — even after trim/lowercase. These still get synced (as
   *  profile_id: null, technician_name: the raw ticket text — see
   *  migration 0142), just surfaced separately so a real name mismatch is
   *  visible and fixable (e.g. fix that person's Display Name, or their
   *  role, so a future sync links their tickets to a real profile)
   *  instead of looking identical to any other synced entry. */
  unmatchedTechnicians: { name: string; count: number }[];
}

/**
 * Auto-generates mileage entries from COMPLETED tickets — one row per
 * ticket (not a combined daily total), each priced with the same
 * office-to-customer distance calculator already used on the ticket detail
 * page. Always all-time, no date range — every completed ticket this
 * company has ever logged. Safe to re-run: tickets that already produced a
 * row (tracked via mileage_entries.ticket_id, enforced unique by migration
 * 0141) are skipped rather than duplicated.
 *
 * Matches tickets to technicians by NAME, case/whitespace-insensitive — same
 * convention as every other free-text technician match in this app (e.g.
 * AccountingDashboard.tsx's own Tech Payroll employeeByName resolution,
 * resolveTeamLeadOrManager's manager_name match). A ticket whose technician
 * text matches no known technician (wrong/legacy Display Name, or no User
 * Management account at all) still gets synced — profile_id: null,
 * technician_name: the raw ticket text (migration 0142) — rather than
 * silently dropped, so mileage isn't lost just because nobody's fixed that
 * person's profile yet. It's surfaced via unmatchedTechnicians either way.
 *
 * Takes every technician at once and does ONE ticket fetch for all of them,
 * rather than one fetch per technician — both fixes the matching bug above
 * and avoids N separate round-trips for N technicians.
 *
 * "Completed" is deliberately the exact same definition Overall Status's
 * Tech Completion Rate table uses (overallStatusData.ts's techMap
 * builder) — the ticket's own `technician`/`status` fields run through
 * statusGroupOf, NOT the visit-level repair_status Tech Payroll uses. That
 * keeps this in sync with what the user actually sees as "completed" on
 * that dashboard, rather than a different, visit-level notion of done.
 * Redo tickets are NOT excluded here (unlike Tech Payroll) — a redo still
 * involved a real drive, it's only excluded from pay because that's a
 * piece-rate concern, not a mileage one.
 */
export async function syncMileageFromTickets(input: {
  technicians: { profileId: string; fullName: string; branch: string }[];
}): Promise<MileageSyncResult> {
  const result: MileageSyncResult = { created: 0, skipped: 0, errors: [], unmatchedTechnicians: [] };
  const techByNormalizedName = new Map(
    input.technicians.filter((t) => t.fullName.trim()).map((t) => [t.fullName.trim().toLowerCase(), t])
  );
  if (techByNormalizedName.size === 0) return result;

  const [{ data: ticketRows, error: ticketsErr }, { data: syncedRows, error: syncedErr }, mapProvider] = await Promise.all([
    supabase
      .from("tickets")
      .select("id, ticket_no, technician, status, schedule_date, location, account, customer:customers ( address, address2, city, state, zip, phone, email )")
      .not("technician", "is", null),
    supabase.from("mileage_entries").select("ticket_id").not("ticket_id", "is", null),
    getCompanyMapProvider(),
  ]);
  if (ticketsErr) {
    result.errors.push(`Failed to load tickets: ${ticketsErr.message}`);
    return result;
  }
  if (syncedErr) console.error("syncMileageFromTickets (existing sync check) error:", syncedErr.message);
  const alreadySynced = new Set((syncedRows ?? []).map((r: any) => r.ticket_id));

  const allCompletedTickets = (ticketRows ?? []).filter(
    (t: any) => String(t.technician || "").trim() && statusGroupOf(t.status || "") === "completed"
  );

  // Anyone whose completed tickets carry a technician name that isn't a
  // known technician, even after trim/lowercase — still synced below (as an
  // unlinked, profile_id: null entry), just surfaced separately so a real
  // name mismatch is visible and fixable rather than looking like any other
  // synced entry.
  const unmatchedCounts = new Map<string, number>();
  for (const t of allCompletedTickets as any[]) {
    const name = String(t.technician).trim();
    if (!techByNormalizedName.has(name.toLowerCase())) {
      unmatchedCounts.set(name, (unmatchedCounts.get(name) ?? 0) + 1);
    }
  }
  result.unmatchedTechnicians = Array.from(unmatchedCounts.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  const pending = allCompletedTickets.filter((t: any) => !alreadySynced.has(t.id));
  result.skipped = allCompletedTickets.length - pending.length;
  if (pending.length === 0) return result;

  for (const ticket of pending as any[]) {
    const rawName = String(ticket.technician).trim();
    // undefined = no known technician list was even passed in (shouldn't
    // happen, guarded above); null (via ?? null below) = a real "no match".
    const technician = techByNormalizedName.get(rawName.toLowerCase()) ?? null;
    const customer = ticket.customer ?? {};
    const mileageInput: MileageTicketInput = {
      location: ticket.location,
      city: customer.city,
      address: customer.address,
      state: customer.state,
      zip: customer.zip,
      account: ticket.account,
    };
    let miles: number | null = null;
    try {
      miles = await computeOfficeDistanceMiles(mileageInput, mapProvider);
    } catch (err) {
      result.errors.push(`Ticket ${ticket.ticket_no}: ${err instanceof Error ? err.message : "distance lookup failed"}`);
      continue;
    }
    if (miles === null) {
      result.errors.push(`Ticket ${ticket.ticket_no}: no route found — skipped.`);
      continue;
    }

    const fullAddress = [customer.address, customer.address2, [customer.city, customer.state].filter(Boolean).join(", "), customer.zip]
      .filter((part: unknown) => typeof part === "string" && part.trim())
      .join(", ");
    const googleMapLink = fullAddress
      ? `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(fullAddress)}`
      : "";

    const { error: insertErr } = await supabase.from("mileage_entries").insert({
      profile_id: technician?.profileId ?? null,
      technician_name: technician ? null : rawName,
      branch: ticket.location || technician?.branch || "Unassigned",
      work_date: ticket.schedule_date,
      address: fullAddress || "(no address on file)",
      contact_number: customer.phone || null,
      email: customer.email || null,
      total_mileage: Math.round(miles * 10) / 10,
      google_map_link: googleMapLink || null,
      created_by_name: "Auto-sync",
      ticket_id: ticket.id,
      ticket_no: ticket.ticket_no,
      source: "auto",
    });
    if (insertErr) {
      // Unique-violation on ticket_id means another sync run already logged
      // it a moment ago (race) — treat as skipped, not a real failure.
      if (insertErr.code === "23505") result.skipped++;
      else result.errors.push(`Ticket ${ticket.ticket_no}: ${insertErr.message}`);
      continue;
    }
    result.created++;
  }

  return result;
}
