/**
 * Technician mileage log (migration 0138) — a manual entry log, PLUS
 * (migration 0141) an optional auto-sync path that derives entries from
 * every ticket assigned to a technician, regardless of status. Manual
 * entries are typed in directly;
 * auto-synced ones (source: "auto") are generated by syncMileageFromTickets
 * below, reusing the same office-to-customer distance calculator already
 * used on the ticket detail page (mapEngine.ts's computeOfficeDistanceMiles)
 * rather than any new mileage math. Edited on Accounting Dashboard's
 * Mileage tab.
 */

import { supabase } from "./client";
import { getCompanyMapProvider } from "./companySettings";
import { computeOfficeDistanceMiles, type MileageTicketInput } from "@/lib/mapEngine";

export interface MileageEntry {
  id: string;
  /** Null when this entry was auto-synced for a technician name that
   *  matched no real profile — see technicianName and migration 0142. */
  profileId: string | null;
  /** Raw ticket technician text, set only when profileId is null — the
   *  display fallback for an unmatched auto-synced entry. Manual entries
   *  (which always require picking a real profile) never set this. */
  technicianName: string | null;
  branch: string;
  workDate: string;
  address: string;
  contactNumber: string | null;
  email: string | null;
  totalMileage: number;
  googleMapLink: string | null;
  createdByName: string | null;
  createdAt: string;
  ticketId: string | null;
  /** Human-readable ticket number, set only on auto-synced entries — see migration 0143. */
  ticketNo: string | null;
  /** The ticket's status AT SYNC TIME — a snapshot, not live; see migration 0147. */
  ticketStatus: string | null;
  source: "manual" | "auto";
  /** Payroll override set via the On Hold action — see migration 0148 and
   *  setMileageEntryPayrollExcluded. While true, this ticket never counts
   *  toward the technician's "Completed Tickets" pay, even if its status
   *  later becomes completed. Reversible — toggling it back off restores
   *  normal pay counting. */
  payrollExcluded: boolean;
  payrollExcludedAt: string | null;
  payrollExcludedByName: string | null;
  /** "manual" (Mileage tab's On Hold button) or "no_photos" (automatic — see
   *  reconcileMileageNoPhotoHolds). Null when not excluded. Lets the
   *  automatic rule know never to touch a human's manual hold, and lets a
   *  human's "take it off hold" always win even with no photo. Migration 0181. */
  payrollHoldReason: "manual" | "no_photos" | null;
}

function mapRow(r: any): MileageEntry {
  return {
    id: r.id,
    profileId: r.profile_id ?? null,
    technicianName: r.technician_name ?? null,
    branch: r.branch,
    workDate: r.work_date,
    address: r.address,
    contactNumber: r.contact_number ?? null,
    email: r.email ?? null,
    totalMileage: Number(r.total_mileage) || 0,
    googleMapLink: r.google_map_link ?? null,
    createdByName: r.created_by_name ?? null,
    createdAt: r.created_at,
    ticketId: r.ticket_id ?? null,
    ticketNo: r.ticket_no ?? null,
    ticketStatus: r.ticket_status ?? null,
    source: r.source === "auto" ? "auto" : "manual",
    payrollExcluded: !!r.payroll_excluded,
    payrollExcludedAt: r.payroll_excluded_at ?? null,
    payrollExcludedByName: r.payroll_excluded_by_name ?? null,
    payrollHoldReason: r.payroll_hold_reason === "manual" || r.payroll_hold_reason === "no_photos" ? r.payroll_hold_reason : null,
  };
}

const ENTRY_COLUMNS =
  "id, profile_id, technician_name, branch, work_date, address, contact_number, email, total_mileage, google_map_link, created_by_name, created_at, ticket_id, ticket_no, ticket_status, source, payroll_excluded, payroll_excluded_at, payroll_excluded_by_name, payroll_hold_reason";

/** All mileage entries for the caller's company (RLS-scoped), newest first. */
export async function getMileageEntries(): Promise<MileageEntry[]> {
  const { data, error } = await supabase
    .from("mileage_entries")
    .select(ENTRY_COLUMNS)
    .order("work_date", { ascending: false });
  if (error) {
    console.error("getMileageEntries error:", error.message);
    return [];
  }
  return (data ?? []).map(mapRow);
}

/**
 * Toggles the "don't pay for this ticket while on hold" override — see
 * MileageEntry.payrollExcluded. Reversible: un-excluding just clears the
 * flag; it doesn't need to restore anything else, since the exclusion is
 * checked live by getTechCompletedRepairCounts, not baked into a stored pay
 * amount anywhere.
 */
export async function setMileageEntryPayrollExcluded(
  id: string,
  excluded: boolean,
  excludedByProfileId: string | null,
  excludedByName: string | null
): Promise<void> {
  const { error } = await supabase
    .from("mileage_entries")
    .update({
      payroll_excluded: excluded,
      payroll_excluded_at: excluded ? new Date().toISOString() : null,
      payroll_excluded_by: excluded ? excludedByProfileId : null,
      payroll_excluded_by_name: excluded ? excludedByName : null,
      // Manual always wins — a human explicitly deciding "off" should never
      // get silently re-held by the automatic no-photos rule afterward.
      payroll_hold_reason: excluded ? "manual" : null,
    })
    .eq("id", id);
  if (error) throw new Error(error.message);
}

/**
 * Applies the "no photos uploaded yet → hold this ticket's pay" rule —
 * called from Accounting Dashboard's Mileage tab once its batch photo
 * check (hasTicketPhotos, storage.ts) resolves for a set of entries.
 * Never touches a row whose payroll_hold_reason is "manual" — that's a
 * human's call, not this rule's to make or unmake. Silent (no
 * notifications) since this can fire many times as photos trickle in;
 * the manual toggle's own notification flow stays exactly as it was.
 * Returns how many rows actually changed, for a status message.
 */
export async function reconcileMileageNoPhotoHolds(
  entries: { id: string; payrollExcluded: boolean; payrollHoldReason: "manual" | "no_photos" | null }[],
  hasPhotosByEntryId: Map<string, boolean>
): Promise<number> {
  let changed = 0;
  for (const entry of entries) {
    if (entry.payrollHoldReason === "manual") continue;
    const hasPhotos = hasPhotosByEntryId.get(entry.id);
    if (hasPhotos === undefined) continue;
    const shouldHold = !hasPhotos;
    const isCurrentlyAutoHeld = entry.payrollExcluded && entry.payrollHoldReason === "no_photos";
    if (shouldHold === isCurrentlyAutoHeld) continue;
    const { error } = await supabase
      .from("mileage_entries")
      .update({
        payroll_excluded: shouldHold,
        payroll_excluded_at: shouldHold ? new Date().toISOString() : null,
        payroll_excluded_by: null,
        payroll_excluded_by_name: shouldHold ? "Auto (no photos)" : null,
        payroll_hold_reason: shouldHold ? "no_photos" : null,
      })
      .eq("id", entry.id);
    if (error) console.error(`reconcileMileageNoPhotoHolds (${entry.id}):`, error.message);
    else changed++;
  }
  return changed;
}

export async function deleteMileageEntry(id: string): Promise<void> {
  const { error } = await supabase.from("mileage_entries").delete().eq("id", id);
  if (error) throw new Error(error.message);
}

export interface MileageSyncResult {
  created: number;
  skipped: number;
  errors: string[];
  /** Tickets whose technician text didn't match ANY technician passed in —
   *  even after trim/lowercase. These still get synced (as profile_id:
   *  null, technician_name: the raw ticket text — see migration 0142),
   *  just surfaced separately so a real name mismatch is visible and
   *  fixable (e.g. fix that person's Display Name, or their role, so a
   *  future sync links their tickets to a real profile) instead of
   *  looking identical to any other synced entry. */
  unmatchedTechnicians: { name: string; count: number }[];
}

/**
 * Auto-generates mileage entries from EVERY ticket assigned to a
 * technician — not just completed ones, since a drive happened regardless
 * of whether the job finished, is still open, or got cancelled after the
 * tech arrived — one row per ticket (not a combined daily total), each
 * priced with the same office-to-customer distance calculator already used
 * on the ticket detail page. All-time by default (omit fromDate/toDate) or
 * scoped to a schedule_date window when the caller passes one. Safe to re-run: tickets that already
 * produced a row (tracked via mileage_entries.ticket_id, enforced unique
 * by migration 0141) are skipped rather than duplicated. Tickets with no
 * schedule_date are skipped too (mileage_entries.work_date is required —
 * there's no date to log the drive under).
 *
 * Matches tickets to technicians by NAME, case/whitespace-insensitive — same
 * convention as every other free-text technician match in this app (e.g.
 * AccountingDashboard.tsx's own Tech Payroll employeeByName resolution,
 * resolveTeamLeadOrManager's manager_name match). A ticket whose technician
 * text matches no known technician (wrong/legacy Display Name, or no User
 * Management account at all) still gets synced — profile_id: null,
 * technician_name: the raw ticket text (migration 0142) — rather than
 * silently dropped, so mileage isn't lost just because nobody's fixed that
 * person's profile yet. It's surfaced via unmatchedTechnicians either way.
 *
 * Takes every technician at once and does ONE ticket fetch for all of them,
 * rather than one fetch per technician — both fixes the matching bug above
 * and avoids N separate round-trips for N technicians.
 */
export async function syncMileageFromTickets(input: {
  technicians: { profileId: string; fullName: string; branch: string; phone?: string; email?: string; homeAddress?: string }[];
  /** Optional schedule_date bounds (inclusive, "YYYY-MM-DD"). Omit either (or both) for the original all-time behavior. */
  fromDate?: string;
  toDate?: string;
}): Promise<MileageSyncResult> {
  const result: MileageSyncResult = { created: 0, skipped: 0, errors: [], unmatchedTechnicians: [] };
  const techByNormalizedName = new Map(
    input.technicians.filter((t) => t.fullName.trim()).map((t) => [t.fullName.trim().toLowerCase(), t])
  );
  if (techByNormalizedName.size === 0) return result;

  let ticketsQuery = supabase
    .from("tickets")
    .select("id, ticket_no, technician, status, schedule_date, location, account, customer:customers ( address, address2, city, state, zip, phone, email )")
    .not("technician", "is", null);
  if (input.fromDate) ticketsQuery = ticketsQuery.gte("schedule_date", input.fromDate);
  if (input.toDate) ticketsQuery = ticketsQuery.lte("schedule_date", input.toDate);

  const [{ data: ticketRows, error: ticketsErr }, { data: syncedRows, error: syncedErr }, mapProvider] = await Promise.all([
    ticketsQuery,
    supabase.from("mileage_entries").select("ticket_id").not("ticket_id", "is", null),
    getCompanyMapProvider(),
  ]);
  if (ticketsErr) {
    result.errors.push(`Failed to load tickets: ${ticketsErr.message}`);
    return result;
  }
  if (syncedErr) console.error("syncMileageFromTickets (existing sync check) error:", syncedErr.message);
  const alreadySynced = new Set((syncedRows ?? []).map((r: any) => r.ticket_id));

  // Every ticket with a technician assigned and an actual date to log the
  // drive under — status doesn't matter, an open/cancelled ticket still
  // involved a real drive.
  const allAssignedTickets = (ticketRows ?? []).filter(
    (t: any) => String(t.technician || "").trim() && t.schedule_date
  );

  // Anyone whose tickets carry a technician name that isn't a known
  // technician, even after trim/lowercase — still synced below (as an
  // unlinked, profile_id: null entry), just surfaced separately so a real
  // name mismatch is visible and fixable rather than looking like any other
  // synced entry.
  const unmatchedCounts = new Map<string, number>();
  for (const t of allAssignedTickets as any[]) {
    const name = String(t.technician).trim();
    if (!techByNormalizedName.has(name.toLowerCase())) {
      unmatchedCounts.set(name, (unmatchedCounts.get(name) ?? 0) + 1);
    }
  }
  result.unmatchedTechnicians = Array.from(unmatchedCounts.entries())
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);

  const pending = allAssignedTickets.filter((t: any) => !alreadySynced.has(t.id));
  result.skipped = allAssignedTickets.length - pending.length;
  if (pending.length === 0) return result;

  for (const ticket of pending as any[]) {
    const rawName = String(ticket.technician).trim();
    // undefined = no known technician list was even passed in (shouldn't
    // happen, guarded above); null (via ?? null below) = a real "no match".
    const technician = techByNormalizedName.get(rawName.toLowerCase()) ?? null;
    const customer = ticket.customer ?? {};
    const mileageInput: MileageTicketInput = {
      location: ticket.location,
      city: customer.city,
      address: customer.address,
      state: customer.state,
      zip: customer.zip,
      account: ticket.account,
    };
    let miles: number | null = null;
    try {
      miles = await computeOfficeDistanceMiles(mileageInput, mapProvider);
    } catch (err) {
      result.errors.push(`Ticket ${ticket.ticket_no}: ${err instanceof Error ? err.message : "distance lookup failed"}`);
      continue;
    }
    if (miles === null) {
      result.errors.push(`Ticket ${ticket.ticket_no}: no route found — skipped.`);
      continue;
    }

    const fullAddress = [customer.address, customer.address2, [customer.city, customer.state].filter(Boolean).join(", "), customer.zip]
      .filter((part: unknown) => typeof part === "string" && part.trim())
      .join(", ");
    const googleMapLink = fullAddress
      ? `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(fullAddress)}`
      : "";

    const { error: insertErr } = await supabase.from("mileage_entries").insert({
      profile_id: technician?.profileId ?? null,
      technician_name: technician ? null : rawName,
      branch: ticket.location || technician?.branch || "Unassigned",
      work_date: ticket.schedule_date,
      // The technician's OWN contact info, not the customer's — Address/
      // Contact Number/Email here answer "who drove and how do we reach
      // them," which the customer's job-site details never were. Google
      // Map Link below still points at the customer's site (for driving
      // directions there), unaffected by this.
      address: technician?.homeAddress || "(no address on file)",
      contact_number: technician?.phone || null,
      email: technician?.email || null,
      total_mileage: Math.round(miles * 10) / 10,
      google_map_link: googleMapLink || null,
      created_by_name: "Auto-sync",
      ticket_id: ticket.id,
      ticket_no: ticket.ticket_no,
      ticket_status: ticket.status,
      source: "auto",
    });
    if (insertErr) {
      // Unique-violation on ticket_id means another sync run already logged
      // it a moment ago (race) — treat as skipped, not a real failure.
      if (insertErr.code === "23505") result.skipped++;
      else result.errors.push(`Ticket ${ticket.ticket_no}: ${insertErr.message}`);
      continue;
    }
    result.created++;
  }

  return result;
}
