/**
 * Fill Master Independent Contractor Subcontractor Agreement Addendum — the
 * recipient (Subcontractor / Contractor, the `employee` slot) opens this
 * from the deep link HR's "Send Request" flow sends. They fill Position
 * Level, Guaranteed Minimum Baseline Payout, and their printed name, then
 * sign. The document then routes to the Company HR Representative and the
 * three managerial witnesses (SignContractorAddendumPage.tsx) — see
 * contractorAddendumFormTemplate.ts for the slot chain.
 *
 * The PDF has no source asset — it's generated by contractorAddendumPdf.ts,
 * which also hands back the on-page rectangle of every blank so the input
 * overlays land exactly on the underscore lines.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "@tanstack/react-router";
import { ChevronLeft, Loader2 } from "lucide-react";
import { AppHeader } from "@/components/Header";
import { useAuth } from "@/lib/auth";
import { getMyProfileId } from "@/lib/supabase/users";
import { getSignableDocument, signDocument, type SignableDocument } from "@/lib/supabase/signableDocuments";
import { uploadSignableDocumentSignature, uploadContractorAddendumForm, refreshStorageAuthToken } from "@/lib/firebase/storage";
import {
  loadBlankContractorAddendum,
  fillContractorAddendumPdf,
  type ContractorAddendumLayout,
} from "@/lib/contractorAddendumPdf";
import {
  blankContractorAddendumData,
  canManageContractorAddendum,
  type ContractorAddendumFormData,
} from "@/lib/contractorAddendumFormTemplate";
import { getOrCreateDmThread, sendMessage } from "@/lib/supabase/messaging";
import { logActivity } from "@/lib/supabase/hrActivityLog";
import { getHrNotificationSettings } from "@/lib/supabase/companySettings";
import { notifyHrRoleUsers } from "@/lib/supabase/hrRoleNotify";
import { useSignaturePad } from "@/hooks/useSignaturePad";
import { SignaturePadControls } from "@/components/SignaturePad";
import { ContractorAddendumCanvas, rectStyle } from "@/components/ContractorAddendumCanvas";

interface Props {
  docId: string;
}

const fmtDate = (d: Date) => `${String(d.getMonth() + 1).padStart(2, "0")}/${String(d.getDate()).padStart(2, "0")}/${d.getFullYear()}`;
const overlayInputCls =
  "bg-blue-50/70 border border-blue-300/70 rounded-[2px] outline-none px-0.5 font-bold font-sans text-[#00008B] focus:bg-blue-100/80 focus:border-blue-400";

export function FillContractorAddendumPage({ docId }: Props) {
  const { ready, uid, displayName, role, extraRoles } = useAuth();
  const [myProfileId, setMyProfileId] = useState<string | null>(null);
  const [doc, setDoc] = useState<SignableDocument | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitted, setSubmitted] = useState(false);

  const [blank, setBlank] = useState<{ bytes: Uint8Array; layout: ContractorAddendumLayout } | null>(null);

  const [positionLevel, setPositionLevel] = useState("");
  const [baselinePayout, setBaselinePayout] = useState("");
  const [contractorName, setContractorName] = useState("");
  const sigPad = useSignaturePad({ defaultName: contractorName, width: 440, height: 100 });
  const today = useMemo(() => fmtDate(new Date()), []);
  const nameSeeded = useRef(false);

  useEffect(() => {
    if (!ready || !uid) return;
    let cancelled = false;
    (async () => {
      setLoading(true);
      setError(null);
      try {
        const [profileId, document, built] = await Promise.all([
          getMyProfileId(uid),
          getSignableDocument(docId),
          loadBlankContractorAddendum(),
        ]);
        if (cancelled) return;
        setMyProfileId(profileId);
        setBlank(built);
        if (!document || document.documentType !== "contractor_addendum") {
          setError("This document doesn't exist or has been removed.");
        } else {
          setDoc(document);
          const existing = document.formData as Partial<ContractorAddendumFormData>;
          if (existing.positionLevel) setPositionLevel(existing.positionLevel);
          if (existing.baselinePayout) setBaselinePayout(existing.baselinePayout);
          const priorName = existing.signerNames?.employee || document.recipientName || "";
          if (priorName && !nameSeeded.current) {
            setContractorName(priorName);
            nameSeeded.current = true;
          }
        }
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Failed to load document.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [ready, uid, docId]);

  const isRecipient = !!doc && !!myProfileId && doc.recipientId === myProfileId;
  // Admin / Super Admin (and platform Super Super Admin) may fill and sign
  // the addendum even when it isn't routed to them — see
  // canManageContractorAddendum.
  const canManage = canManageContractorAddendum(role, extraRoles);

  const validate = (): string | null => {
    if (!positionLevel.trim()) return "Enter the Position Level.";
    if (!baselinePayout.trim()) return "Enter the Guaranteed Minimum Baseline Payout.";
    if (!contractorName.trim()) return "Enter your printed name.";
    if (!sigPad.hasContent()) return "Please add your signature.";
    return null;
  };

  const handleSubmit = async () => {
    if (!doc || !myProfileId) return;
    const v = validate();
    if (v) {
      setError(v);
      return;
    }
    const dataUrl = sigPad.toDataURL();
    if (!dataUrl) {
      setError("Please add your signature.");
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const companyId = doc.companyId;
      await refreshStorageAuthToken();
      const signedAt = new Date().toISOString();
      const sigBytes = new Uint8Array(await (await fetch(dataUrl)).arrayBuffer());

      const finalData: ContractorAddendumFormData = {
        ...blankContractorAddendumData(),
        ...(doc.formData as Partial<ContractorAddendumFormData>),
        employeeId: doc.recipientId ?? "",
        positionLevel: positionLevel.trim(),
        baselinePayout: baselinePayout.trim(),
        signerNames: { ...(doc.formData as ContractorAddendumFormData).signerNames, employee: contractorName.trim() },
        datesSigned: { ...(doc.formData as ContractorAddendumFormData).datesSigned, employee: signedAt },
        signatureDataUrls: { ...(doc.formData as ContractorAddendumFormData).signatureDataUrls, employee: dataUrl },
      };

      const signatureUrl = await uploadSignableDocumentSignature(companyId, doc.id, "employee", dataUrl);
      const pdfBytes = await fillContractorAddendumPdf(finalData, { employee: sigBytes });
      const pdfUrl = await uploadContractorAddendumForm(companyId, contractorName.trim(), new Blob([pdfBytes as unknown as BlobPart], { type: "application/pdf" }));

      const entry = { name: displayName || contractorName.trim() || "Signed", url: signatureUrl, signedAt };
      await signDocument(doc.id, "employee", entry, pdfUrl, finalData as unknown as Record<string, any>);

      if (doc.createdBy) {
        const thread = await getOrCreateDmThread(myProfileId, doc.createdBy);
        const filename = `Master Independent Contractor Subcontractor Agreement Addendum - ${contractorName.trim()}.pdf`;
        await sendMessage({
          dmThreadId: thread.id,
          senderId: myProfileId,
          senderName: displayName || "Contractor",
          body: `📄 Master Independent Contractor Subcontractor Agreement Addendum for ${contractorName.trim()} has been signed by the Contractor — ready to route to the Company HR Representative: [${filename}](${pdfUrl})`,
        });
      }

      getHrNotificationSettings()
        .then(({ taxForms }) => {
          if (!taxForms) return;
          const excludeIds = doc.createdBy ? [doc.createdBy] : [];
          void notifyHrRoleUsers(myProfileId, displayName || "Contractor", excludeIds, `📄 Master Independent Contractor Subcontractor Agreement Addendum for ${contractorName.trim()} has been signed by the Contractor — route it to the next signer.`);
        })
        .catch((err) => console.error("[contractor-addendum] hr notify check failed:", err));

      setDoc({ ...doc, status: "signed", pdfUrl, formData: finalData as unknown as Record<string, any>, signatures: { employee: entry }, signedAt });
      void logActivity({ action: "contractor_addendum_signed", targetType: "employee", targetLabel: contractorName.trim(), details: { slot: "employee" } });
      setSubmitted(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to submit form.");
    } finally {
      setSubmitting(false);
    }
  };

  const renderOverlay = (pageIndex: number, scale: number) => {
    if (!blank) return null;
    const { layout } = blank;
    const emp = layout.signatures.employee;
    return (
      <>
        {pageIndex === layout.positionLevel.page && (
          <input
            style={{ ...rectStyle(layout.positionLevel, scale), fontSize: `${8 * scale}px` }}
            className={overlayInputCls}
            value={positionLevel}
            onChange={(e) => setPositionLevel(e.target.value)}
            placeholder="Position Level"
          />
        )}
        {pageIndex === layout.baselinePayout.page && (
          <input
            style={{ ...rectStyle(layout.baselinePayout, scale), fontSize: `${8 * scale}px` }}
            className={overlayInputCls}
            value={baselinePayout}
            inputMode="numeric"
            onChange={(e) => setBaselinePayout(e.target.value.replace(/[^\d.,]/g, ""))}
            placeholder="0.00"
          />
        )}
        {emp && pageIndex === emp.name.page && (
          <input
            style={{ ...rectStyle(emp.name, scale), fontSize: `${8 * scale}px` }}
            className={overlayInputCls}
            value={contractorName}
            onChange={(e) => setContractorName(e.target.value)}
            placeholder="Your printed name"
          />
        )}
        {emp && pageIndex === emp.sig.page && (
          <>
            <canvas
              {...sigPad.canvasProps}
              style={rectStyle(emp.sig, scale)}
            />
            <div style={{ ...rectStyle(emp.date, scale), fontSize: `${8 * scale}px` }} className="flex items-center font-bold text-[#00008B] pointer-events-none">
              {today}
            </div>
          </>
        )}
      </>
    );
  };

  return (
    <div className="min-h-screen bg-background">
      <AppHeader />
      <main className="max-w-4xl mx-auto p-4">
        <Link to="/home" className="btn text-xs px-2.5 py-1.5 flex items-center gap-1 w-fit mb-4">
          <ChevronLeft className="h-3.5 w-3.5" /> Home
        </Link>

        {loading ? (
          <div className="panel p-8 text-center text-sm text-muted-foreground flex items-center justify-center gap-2">
            <Loader2 className="h-4 w-4 animate-spin" /> Loading document…
          </div>
        ) : error && !doc ? (
          <div className="panel p-6 text-sm text-red-300">{error}</div>
        ) : !doc ? null : !isRecipient && !canManage ? (
          <div className="panel p-6 text-sm text-muted-foreground">This document isn't addressed to your account.</div>
        ) : submitted || doc.status === "signed" || doc.status === "confirmed" ? (
          <div className="panel p-6 text-center">
            <p className="text-sm font-semibold mb-2">✅ Submitted{submitted ? " and sent back to HR" : ""}.</p>
            <p className="text-xs text-muted-foreground mb-2">HR will route it to the Company HR Representative and the managerial witnesses for their signatures.</p>
            {doc.pdfUrl && (
              <a href={doc.pdfUrl} target="_blank" rel="noreferrer noopener" className="text-blue-300 hover:text-blue-200 underline text-sm">
                View the completed PDF
              </a>
            )}
          </div>
        ) : (
          <div className="panel p-4">
            <p className="text-xs text-muted-foreground mb-3">
              Fill in the Position Level, the Guaranteed Minimum Baseline Payout, and your printed name, review the agreement, add your signature, then submit.
            </p>

            <ContractorAddendumCanvas bytes={blank?.bytes ?? null} renderOverlay={renderOverlay} />

            <div className="flex items-center justify-center mt-2">
              <SignaturePadControls pad={sigPad} />
            </div>

            {error && (
              <p className="text-xs text-red-300 bg-red-500/10 border border-red-500/30 rounded-md px-2.5 py-2 mt-3">{error}</p>
            )}

            <button
              onClick={handleSubmit}
              disabled={submitting}
              className="btn text-sm px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white mt-3 disabled:opacity-50"
            >
              {submitting ? "Submitting…" : "Submit to HR"}
            </button>
          </div>
        )}
      </main>
    </div>
  );
}
