/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimecardRouteImport } from './routes/timecard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketTicketNoRouteImport } from './routes/ticket.$ticketNo'
import { Route as MModuleRouteImport } from './routes/m.$module'
import { Route as MModuleSubmoduleRouteImport } from './routes/m.$module.$submodule'

const TimecardRoute = TimecardRouteImport.update({
  id: '/timecard',
  path: '/timecard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketNoRoute = TicketTicketNoRouteImport.update({
  id: '/ticket/$ticketNo',
  path: '/ticket/$ticketNo',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleRoute = MModuleRouteImport.update({
  id: '/m/$module',
  path: '/m/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const MModuleSubmoduleRoute = MModuleSubmoduleRouteImport.update({
  id: '/$submodule',
  path: '/$submodule',
  getParentRoute: () => MModuleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/timecard': typeof TimecardRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/timecard': typeof TimecardRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/timecard': typeof TimecardRoute
  '/m/$module': typeof MModuleRouteWithChildren
  '/ticket/$ticketNo': typeof TicketTicketNoRoute
  '/m/$module/$submodule': typeof MModuleSubmoduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/timecard'
    | '/m/$module'
    | '/ticket/$ticketNo'
    | '/m/$module/$submodule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/timecard'
    | '/m/$module'
    | '/ticket/$ticketNo'
    | '/m/$module/$submodule'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/timecard'
    | '/m/$module'
    | '/ticket/$ticketNo'
    | '/m/$module/$submodule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LandingRoute: typeof LandingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TimecardRoute: typeof TimecardRoute
  MModuleRoute: typeof MModuleRouteWithChildren
  TicketTicketNoRoute: typeof TicketTicketNoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timecard': {
      id: '/timecard'
      path: '/timecard'
      fullPath: '/timecard'
      preLoaderRoute: typeof TimecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketNo': {
      id: '/ticket/$ticketNo'
      path: '/ticket/$ticketNo'
      fullPath: '/ticket/$ticketNo'
      preLoaderRoute: typeof TicketTicketNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module': {
      id: '/m/$module'
      path: '/m/$module'
      fullPath: '/m/$module'
      preLoaderRoute: typeof MModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$module/$submodule': {
      id: '/m/$module/$submodule'
      path: '/$submodule'
      fullPath: '/m/$module/$submodule'
      preLoaderRoute: typeof MModuleSubmoduleRouteImport
      parentRoute: typeof MModuleRoute
    }
  }
}

interface MModuleRouteChildren {
  MModuleSubmoduleRoute: typeof MModuleSubmoduleRoute
}

const MModuleRouteChildren: MModuleRouteChildren = {
  MModuleSubmoduleRoute: MModuleSubmoduleRoute,
}

const MModuleRouteWithChildren =
  MModuleRoute._addFileChildren(MModuleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LandingRoute: LandingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TimecardRoute: TimecardRoute,
  MModuleRoute: MModuleRouteWithChildren,
  TicketTicketNoRoute: TicketTicketNoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
